---
? ''
: octodns:
    cloudflare:
      proxied: false
  ttl: 300
  type: A
  value: 34.67.190.70
one:
  octodns:
    cloudflare:
      proxied: false
  ttl: 300
  type: CNAME
  value: mbtest.ga.
subdomainarecords:
- ttl: 300
  type: A
  value: 34.67.190.70
two:
  octodns:
    cloudflare:
      proxied: true
  ttl: 1
  type: A
  value: 34.67.190.70
