on: pull_request
name: Test on pull request
jobs:
  octodnsTest:
    name: Octodns Test on PR
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: octodns test
      uses: docker://parkr/octodns:v0.9.5
      env:
        CLOUDFLARE_EMAIL: ${{ secrets.CLOUDFLARE_EMAIL }}
        CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
      with:
        args: octodns-sync --config-file ./config/production.yaml
